### Numpy

NumPy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [4]:
import numpy as np

# create arrays in numpy
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([[1, 2, 3], [4, 5, 6]])

print("Array 1:", array1)
print("Array 2:\n", array2)

Array 1: [1 2 3 4 5]
Array 2:
 [[1 2 3]
 [4 5 6]]


In [5]:
print(type(array1)) # <class 'numpy.ndarray'>
print(array1.shape) # (5,)
print(array2.shape) # (2, 3)

<class 'numpy.ndarray'>
(5,)
(2, 3)


In [8]:
print(array1.size)
print(array2.size)

5
6


In [17]:
array2=np.array([1,2,3,4,5])
print(array2.shape) # (5,1)
print("Array 2 before reshape:\n", array2)
array2 = array2.reshape(5,1) # reshaping array to 5 rows and 1 column
print("\nArray 2 after reshape:\n", array2)
print(array2.shape) # (5,1)

(5,)
Array 2 before reshape:
 [1 2 3 4 5]

Array 2 after reshape:
 [[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [24]:
# 1d to 2d array

arr=np.array([1,2,3,4,5])
arr=arr.reshape(1,5)
print(arr)

[[1 2 3 4 5]]


In [25]:
# 2d array

arr2=np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [27]:
x=np.arange(1,11,2).reshape(5,1)
print(x)

[[1]
 [3]
 [5]
 [7]
 [9]]


In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# Indentity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
# Attributes of numpy array

arr=np.array([[1,2,3],[4,5,6]])
print("Array: \n", arr)
print("\n\nShape: \n", arr.shape)
print("\n\nNumber of dimensions: \n", arr.ndim)
print("\n\nSize (Number of elements): \n", arr.size)
print("\n\nData type: \n", arr.dtype)
print("\n\nItem size (in bytes): \n", arr.itemsize)
print("\n\nType: \n", type(arr))

Array: 
 [[1 2 3]
 [4 5 6]]


Shape: 
 (2, 3)


Number of dimensions: 
 2


Size (Number of elements): 
 6


Data type: 
 int64


Item size (in bytes): 
 8


Type: 
 <class 'numpy.ndarray'>


In [38]:
# Numpy vectorized operations and universal functions in numpy
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Addition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)
print("Exponentiation:", a ** 2)
print("Square Root of b:", np.sqrt(b))
print("Sine of a:", np.sin(a))
print("Cosine of b:", np.cos(b))
print("Logarithm of b:", np.log(b))
print("Exponential of a:", np.exp(a))
print("Maximum of a and b:", np.maximum(a, b))
print("Minimum of a and b:", np.minimum(a, b))
print("Mean of a:", np.mean(a))
print("Standard Deviation of b:", np.std(b))
print("Dot Product of a and b:", np.dot(a, b))
print("Sum of elements in a:", np.sum(a))
print("Cumulative Sum of b:", np.cumsum(b))
print("Sorting a:", np.sort(a))
print("Unique elements in b:", np.unique(b))
print("Reshaped to 2x2:\n", a.reshape(2,2))
print("Transpose of a reshaped to 2x2:\n", a.reshape(2,2).T)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Exponentiation: [ 1  4  9 16]
Square Root of b: [3.16227766 4.47213595 5.47722558 6.32455532]
Sine of a: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Cosine of b: [-0.83907153  0.40808206  0.15425145 -0.66693806]
Logarithm of b: [2.30258509 2.99573227 3.40119738 3.68887945]
Exponential of a: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Maximum of a and b: [10 20 30 40]
Minimum of a and b: [1 2 3 4]
Mean of a: 2.5
Standard Deviation of b: 11.180339887498949
Dot Product of a and b: 300
Sum of elements in a: 10
Cumulative Sum of b: [ 10  30  60 100]
Sorting a: [1 2 3 4]
Unique elements in b: [10 20 30 40]
Reshaped to 2x2:
 [[1 2]
 [3 4]]
Transpose of a reshaped to 2x2:
 [[1 3]
 [2 4]]


In [41]:
# Array slicing and indexing in numpy
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150],
                [160, 170, 180, 190, 200]])

print("Original Array:\n", arr)
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)

Original Array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]
Dimensions: 2
Shape: (4, 5)
Size: 20


In [61]:
print(arr[2:, 1:3])

[[120 130]
 [170 180]]


In [58]:
print(arr[0,0])
print(arr[3:, 1:])  # Slicing rows and columns

10
[[170 180 190 200]]


In [60]:
print(arr[0:2, 2:])

[[ 30  40  50]
 [ 80  90 100]]


In [63]:
# Modifying array elements
arr[0, 0] = 999
arr[2:, 3:] = 555
print("Modified Array:\n", arr)

Modified Array:
 [[999  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 555 555]
 [160 170 180 555 555]]


In [69]:
# Statistical concepts --> Normalization, Standardization, Covariance, Correlation
# to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(data)
print("Mean:", mean)
median=np.median(data)
print("Median:", median)
std_dev = np.std(data)
print("Standard Deviation:", std_dev)
variance = np.var(data)
print("Variance:", variance)
standardized_data = (data - mean) / std_dev
print("Standardized Data:", standardized_data)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Standardized Data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [78]:
# Logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data_gt_5 = data > 5
print("Data greater than 5:", data_gt_5)
filtered_data = data[data>5]
print("Filtered Data (greater than 5):", filtered_data)

# Correct way: use & for element-wise logical AND with arrays
filtered_data_range = data[(data>4) & (data<9)]
print("Filtered Data (greater than 4 AND less than 9):", filtered_data_range)

Data greater than 5: [False False False False False  True  True  True  True  True]
Filtered Data (greater than 5): [ 6  7  8  9 10]
Filtered Data (greater than 4 AND less than 9): [5 6 7 8]
